### ISSUE TITLE
Typo in predict.py

### ISSUE THREAD

**Issue by MSnelders** [devanshkv/fetch#11]
Hello! 

This is not a bug report, but I didn't know where else to put it. In predict.py, line 36 it says:
"raise ValueError(f'Model only range from a -- j.')", but the models go up to 'k'. So this is a typo that can be changed. 

Furthermore lines 49 & 50 are the same as 35 & 36, not sure what the use of that is. 

Thank you for making FETCH!

**Comment by devanshkv** [comment]
Thanks a lot for using FETCH and bringing this up. 258aa70 fixes both of them.
