### ISSUE TITLE
Run over many directories

### ISSUE THREAD

**Issue by ftorres-ucf** [devanshkv/fetch#17]
**Is your feature request related to a problem? Please describe.**

I am currently running the predict program over many directories. however it takes a substantial time for the model to load for each directory that will be processed.

**Describe the solution you'd like**

I would like the predict to be able to iterate through directories when i supply it with many directories through the -c (--data_dir) option. Basically i supply predict.py -c dir1 -c dir2 and it runs predict over each directory saving the results in that directory without unloading the model until if finishes all directories.

**Describe alternatives you've considered**

The only alternative I have considered to get a feature like this is to move all files into a single directory and keep track of them, have predict run on them, then split the results.csv for each set of files, then move the files and results back. Other than that i have considered reducing the number of independent files in need of processing, however this is not completely possible. 

**Additional context**
![image](https://user-images.githubusercontent.com/83658048/126834273-8bfb4c0a-3dc1-4100-b4c6-f03b6b3ba6f3.png)

**Comment by devanshkv** [comment]
The model gets loaded at https://github.com/devanshkv/fetch/blob/2b006331166f3acf99fe56969d305ba737e76ce4/bin/predict.py#L94

You can load the model before line https://github.com/devanshkv/fetch/blob/2b006331166f3acf99fe56969d305ba737e76ce4/bin/predict.py#L78

And the rest of the code can be moved inside a for loop that loops over your directories.

Sadly we do not have the time to implement this right now, but we would welcome PRs for the same.

**Comment by ftorres-ucf** [comment]
Would there need to be a new branch created for the enhancement of the fetch code?
Possibly merge with the tf2 branch after approval.

**Comment by devanshkv** [comment]
Yes, create a new branch and we will merge it with the tf2 branch post approval.
