### ISSUE TITLE
hello , how can i generate the train file like train_data.hd5?

### ISSUE THREAD

**Issue by aoxipo** [devanshkv/fetch#19]
Hello,Thank you for your contribution and open source spirit， I'm a beginner in deep learning and astronomy FRB from China three gorges University.  I want to run your experiment , how can i generate the train file like train_data.hd5? Do you use fits format data to conversion and generate hd5？

**Comment by ftorres-ucf** [comment]
I am not part of the team, however I am an active user of this software. Generally, you would like to turn the fits file to hd5 for predicting or training of the models. This can be done using the [your_candmaker.py](https://github.com/thepetabyteproject/your) program created by some of the same people that created this software.

**Comment by devanshkv** [comment]
Thanks, @ftorres-ucf that's correct!

**Comment by aoxipo** [comment]
t

> 我不是团队的一员，但我是该软件的活跃用户。通常，您希望将 fits 文件转换为 hd5 以预测或训练模型。这可以使用由创建此软件的某些人创建的[your_candmaker.py](https://github.com/thepetabyteproject/your)程序来完成。

thank you！！！！！！！！！
