### ISSUE TITLE
getting model without internet connection

### ISSUE THREAD

**Issue by caseyjlaw** [devanshkv/fetch#2]
The `fetch/utils.py` defines `get_model` as a call to download the weights from a server at WVU. It would be nice to be able to set this to a model on disk locally.
I am interested in using fetch on a machine that has no internet connection (but I can put files there manually).

**Comment by devanshkv** [comment]
The model files are listed under this [csv](https://github.com/devanshkv/fetch/blob/master/fetch/models/model_list.csv) and can be downloaded by appending this name to `http://psrpop.phys.wvu.edu/download.php?val=.` Once downloaded (for now) you can keep the weights under `$HOME/.keras/models/`. I will add the functionality for the custom path directory in the future.
