### ISSUE TITLE
Website hosting models weight offline

### ISSUE THREAD

**Issue by MSnelders** [devanshkv/fetch#23]
Hi Devansh and Kshitij,

It appears that the website hosting the model weights is offline. 

I was trying to use FETCH on a new machine and I got the following when I wanted to use `predict.py`. 

``` bash
(fetchenv2) m@rk:~/temp$ predict.py -c /home/m/temp/ -m a

Traceback (most recent call last):
  File "/home/m/anaconda3/envs/fetchenv2/bin/predict.py", line 4, in <module>
    __import__('pkg_resources').run_script('fetch==0.2.0', 'predict.py')
  File "/home/m/anaconda3/envs/fetchenv2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/m/anaconda3/envs/fetchenv2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/m/anaconda3/envs/fetchenv2/lib/python3.7/site-packages/fetch-0.2.0-py3.7.egg/EGG-INFO/scripts/predict.py", line 79, in <module>
    model = get_model(args.model)
  File "/home/m/anaconda3/envs/fetchenv2/lib/python3.7/site-packages/fetch-0.2.0-py3.7.egg/fetch/utils.py", line 103, in get_model
    hash_algorithm="md5",
  File "/home/m/anaconda3/envs/fetchenv2/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 250, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on http://psrpop.phys.wvu.edu/download.php?val=ft_DenseNet121_2_dt_Xception_13_256.h5: None -- Bad Gateway
```
For me this happens with all the models, not only model `a`. 
Do you have an estimate on when things will be back online? Thank you in advance.

**Comment by XAO-Maojw** [comment]
I also have this problem and I will be very appreciated if someone could provide a download link

**Comment by devanshkv** [comment]
We are working with out IT folks, will get back to you soon

**Comment by nategarver-daniels** [comment]
As of right now the download links appear to be active, i.e. `wget http://psrpop.phys.wvu.edu/download.php?val=ft_DenseNet121_2_dt_Xception_13_256.h5` works.

**Comment by XAO-Maojw** [comment]
I have downloaded all the models，thank you very much

**Comment by devanshkv** [comment]
Thanks for checking @XAO-Maojw.

**Comment by ruiten22** [comment]
Hi Devansh and Kshitij,

It seems that the download link is inactive again (Exception: URL fetch failure on http://psrpop.phys.wvu.edu/download.php?val=ft_DenseNet121_2_dt_Xception_13_256.h5: 502 -- Bad Gateway)

Is it possible to make it active? Thanks in advance!

**Comment by nategarver-daniels** [comment]
It should be available again.

**Comment by m4rl0nb** [comment]
Hi!
It seems that the 502 error is back again. It also happens in browser if I try the above link. Could you make it available again?
Thank you very much in advance!

**Comment by nategarver-daniels** [comment]
Thanks for the update.  We are currently having hardware issues with the
bare metal that hosts the VM.  I'll ping you here when it's back up.

**Comment by m4rl0nb** [comment]
Alright. Thanks for the quick update!
