### ISSUE TITLE
predict.py model download links appear to be offline

### ISSUE THREAD

**Issue by ruiten22** [devanshkv/fetch#25]
Hi @devanshkv, @KshitijAggarwal and @nategarver-daniels,

I'm unable to use the models in predict.py. The link to download the models seems to be offline again. For models 'a' to 'h', for example, I get the HTTPS Error 502: Bad Gateway.

Could you make the download links active again?

Many thanks in advance, 
Best, 
ruiten22

**Comment by farosikaria** [comment]
PATH_TO_WEIGHTS + model_list["model"][model_index] can be set to None

**Comment by devanshkv** [comment]
Hi,

[Joe Glaser](https://github.com/JPGlaser) should be able to help with this.

Regards,
Devansh
