### ISSUE TITLE
Incompatibility with Tensorflow >=2.5.3

### ISSUE THREAD

**Issue by dantehewitt** [devanshkv/fetch#26]
**Issue**
Since Tensorflow 2.5.3 and above,  `model_from_yaml` has been removed. Would it be possible to update things to make use of `model_from_json` instead? 

**Screenshots**
A screenshot of the related error:

![image](https://user-images.githubusercontent.com/49512826/187676121-0ef34e61-a44a-4d7c-8f68-1fe191dd272d.png)

**Comment by devanshkv** [comment]
Thanks for bringing this up. Would you be interested in creating the JSON model files and sending us a PR?
