### ISSUE TITLE
Cann't find json

### ISSUE THREAD

**Issue by Gstortoise** [devanshkv/fetch#28]
**Describe the bug**
The model have JSON when use tf>2.6, but install doesn't copy the JSON file to models, when use it, it can't find any file

**To Reproduce**
just run it using batch tf2

We need to fix the setup.py 

  `package_data={"fetch": ["models/model_list.csv", "models/*/*yaml"]},`

to 

`package_data={"fetch": ["models/model_list.csv", "models/*/*"]},`

**Comment by sujaymate** [comment]
Hi @devanshkv , I was installing FETCH so thought I will fix this. Accept the PR if it looks fine
