### ISSUE TITLE
why anaconda channel?

### ISSUE THREAD

**Issue by caseyjlaw** [devanshkv/fetch#3]
The installation instructions suggest `conda install -c anaconda ...`. However, that channel is a mirror of the default channel (see https://docs.anaconda.com/anaconda/user-guide/tasks/using-repositories/).
Have you found that forcing this channel is required? If so, why?
I'm partly asking because I have had problems getting conda to make self-consistent builds after upgrading in the way suggested here.

**Comment by KshitijAggarwal** [comment]
There is no `tensorflow-gpu` package in `conda-forge` (see [feedstock](https://conda-forge.org/feedstocks/)), which forces it to use the CPU tensorflow. Hence we use the `anaconda` channel.

**Comment by caseyjlaw** [comment]
My understanding is that "default" and "anaconda" are the same thing. Since "default" is already in everyone's channel list, why does "anaconda" need to be used?

**Comment by devanshkv** [comment]
I've tried installing the dependencies without asking it to install from `default` channel. It installs `tensorflow (base)` from `conda-forge` and `tensorflow-gpu` from the `default` channel, then `keras` tries to use the `theano` backend. When forced to use `tensorflow` backend, the `tensorflow-gpu` from `default` channel doesn't play nice with `conda-forge` `tensorflow (base)`. So we need to have `tensorflow` from the `default` channel as well, hence forcing it to install from anaconda.

**Comment by caseyjlaw** [comment]
I think I had that problem too. I just thought that maybe the instructions should show use `-c defaults` or prioritize the channels differently to demonstrate better anaconda usage. But it sounds like anaconda/conda-forge are just not set up right.
I'll close this issue.
