### ISSUE TITLE
Issue with tensorflow-gpu requirement

### ISSUE THREAD

**Issue by aweaver1fandm** [devanshkv/fetch#34]
tensorflow2 has done away with the tensorflow-gpu package.  It seems like the replacement is tensorflow[and-cuda]

**Comment by devanshkv** [comment]
Hi @aweaver1fandm, I don't have compute resources to test these changes out, would it be possible for you to send a PR?

**Comment by aweaver1fandm** [comment]
Yep. I'll code something up, test it and send the pr

**Comment by devanshkv** [comment]
Thanks @aweaver1fandm
