### ISSUE TITLE
Using predict.py

### ISSUE THREAD

**Issue by parulj3795** [devanshkv/fetch#6]
I have a .fil file, from the Parkes FRB010125 data. The file size is a few MB and contains a single burst. Can I use a model of FETCH to find if the filterbank file contains an FRB or not? If yes, how?

**Comment by devanshkv** [comment]
FETCH is a classifier and cannot be used for detection. You would have to use a single pulse search pipeline like single_pulse_search.py from [PRESTO](https://github.com/scottransom/presto) or [Heimdall](https://sourceforge.net/projects/heimdall-astro/).
